import matplotlib.pyplot as plt
import argparse
import numpy as np
import os

def initialize_plot():
    plt.figure(figsize=(10, 5))
    plt.xlabel('Time steps')
    plt.ylabel('Average Return')

def random(args):

    initialize_plot()
    plt.title('Hopper-random-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_hopper-random-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_hopper-random-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    x = np.linspace(0, 1e6, 201)
    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_hopper-random.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Walker2d-random-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_walker2d-random-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_walker2d-random-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_walker2d-random.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Antmaze-medium-diverse-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_antmaze-medium-diverse-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_antmaze-medium-diverse-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_antmaze-medium-diverse.png".format(args.method))
    plt.show()
    plt.close()

def medium(args):

    initialize_plot()
    plt.title('Hopper-medium-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_hopper-medium-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_hopper-medium-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    x = np.linspace(0, 1e6, 201)
    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_hopper-medium.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Walker2d-medium-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_walker2d-medium-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_walker2d-medium-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_walker2d-medium.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Antmaze-medium-play-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_antmaze-medium-play-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_antmaze-medium-play-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_antmaze-medium-play.png".format(args.method))
    plt.show()
    plt.close()

def expert(args):

    initialize_plot()
    plt.title('Hopper-expert-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_hopper-expert-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_hopper-expert-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    x = np.linspace(0, 1e6, 201)
    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_hopper-expert.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Walker2d-expert-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_walker2d-expert-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_walker2d-expert-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_walker2d-expert.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Maze2d-umaze-v1')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_maze2d-umaze-v1_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_maze2d-umaze-v1_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_maze2d-umaze-v1.png".format(args.method))
    plt.show()
    plt.close()

def medium_replay(args):

    initialize_plot()
    plt.title('Hopper-medium-replay-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_hopper-medium-replay-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_hopper-medium-replay-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    x = np.linspace(0, 1e6, 201)
    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_hopper-medium-replay.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Walker2d-medium-replay-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_walker2d-medium-replay-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_walker2d-medium-replay-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_walker2d-medium-replay.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Maze2d-medium-v1')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_maze2d-medium-v1_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_maze2d-medium-v1_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_maze2d-medium-v1.png".format(args.method))
    plt.show()
    plt.close()

def medium_expert(args):

    initialize_plot()
    plt.title('Hopper-medium-expert-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_hopper-medium-expert-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_hopper-medium-expert-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    x = np.linspace(0, 1e6, 201)
    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_hopper-medium-expert.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Walker2d-medium-expert-v0')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_walker2d-medium-expert-v0_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_walker2d-medium-expert-v0_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_walker2d-medium-expert.png".format(args.method))
    plt.show()
    plt.close()

    initialize_plot()
    plt.title('Maze2d-large-v1')
    rewards = np.array([np.load("./results/baseline/BCQ_baseline_maze2d-large-v1_{}.npy".format(seed)) for seed in range(3)]).transpose()
    rewards_avg = np.mean(rewards, axis = 1)
    rewards_std = np.std(rewards, axis = 1)
    rewards_avg = np.insert(rewards_avg, 0, 0)
    rewards_std = np.insert(rewards_std, 0, 0)

    rewards_GAN = np.array([np.load("./results/{}/BCQ_{}_maze2d-large-v1_{}.npy".format(args.method, args.method, seed)) for seed in range(3)]).transpose()
    rewards_GAN_avg = np.mean(rewards_GAN, axis = 1)
    rewards_GAN_std = np.std(rewards_GAN, axis = 1)
    rewards_GAN_avg = np.insert(rewards_GAN_avg, 0, 0)
    rewards_GAN_std = np.insert(rewards_GAN_std, 0, 0)

    plt.plot(x, rewards_avg, color = 'royalblue', label = 'origin')
    plt.fill_between(x, rewards_avg + rewards_std, rewards_avg - rewards_std, facecolor = 'lightblue')
    plt.plot(x, rewards_GAN_avg, color = 'orange', label = args.method)
    plt.fill_between(x, rewards_GAN_avg + rewards_GAN_std, rewards_GAN_avg - rewards_GAN_std, facecolor = 'bisque')
    plt.legend()
    plt.savefig("./Plots/{}/Compare_maze2d-large-v1.png".format(args.method))
    plt.show()
    plt.close()

if __name__ == "__main__":

    os.makedirs("./Plots", exist_ok=True)

    parser = argparse.ArgumentParser()
    parser.add_argument("--method", default='GAN')
    args = parser.parse_args()

    random(args)
    medium(args)
    expert(args)
    medium_replay(args)
    medium_expert(args)